[MultiClient]
; Enables starting multiple clients.
; Known Support: Alpha

; Enables or disables the mod.
; Default: no
Enabled = yes

[ChatSpam]
; Changes maximum number of repeats for chat messages.
; Known Support: Alpha

; Enables or disables the mod.
; Default: no
Enabled = yes

; Number of repeats allowed. Use 0 to disable spam protection.
; Default: 3
MaxRepeats = 0

[DDrawError]
; Disables DDrawError when the game closes.
; Known Support: Alpha

; Enables or disables the mod.
; Default: no
Enabled = yes

[NoDisclaimer]
; Disables disclaimer on game start.
; Known Support: Alpha, Beta1

; Enables or disables the mod.
; Default: no
Enabled = yes

[CleanText]
; Disables font anti-aliasing, which causes pink borders.
; Known Support: Alpha, Beta1

; Enables or disables the mod.
; Default: no
Enabled = yes

[ConnectAddress]
; Modifies the IP and port the client connects to.
; Known Support: Alpha, Beta1

; Enables or disables the mod.
; Default: no
Enabled = yes

; If enabled, the client accepts "ip:..." and "port:..." command line
; arguments, which override what was configured in this file.
EnableArguments = yes

IP = 127.0.0.1
Port = 7000

[WindowSize]
; Changes the client's window size.
; Known Support: Alpha

; Enables or disables the mod.
; Default: no
Enabled = yes

Width = 1024
Height = 768

[BetterMouseCapture]
; Improves exclusive mouse mode, so the cursor doesn't get stuck inside
; the game's window.
; Known Support: Alpha, Beta1

; Enables or disables the mod.
; Default: yes
Enabled = yes
